# Generated by Django 3.2.3 on 2021-05-26 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_name', models.CharField(max_length=100, verbose_name='Новость')),
                ('new_desc', models.CharField(max_length=1000, verbose_name='Описание')),
                ('new_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('new_edit', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('new_active_flag', models.BooleanField(choices=[(True, 'Активаная'), (False, 'Неактивная')], default=False, verbose_name='Активность новости')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('comment_text', models.CharField(max_length=1000, verbose_name='Комментарий')),
                ('new', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_news.new', verbose_name='Новость')),
            ],
        ),
    ]
